// <auto-generated />
using System;
using Consultation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consultation.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    [Migration("20260811230724_fist migration")]
    partial class fistmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consultation.Model.Entites.RegisterPatient", b =>
                {
                    b.Property<string>("cpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("arrive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("departure")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("cpf");

                    b.ToTable("PatientTable");
                });
#pragma warning restore 612, 618
        }
    }
}
